### ISSUE TITLE
Base url option?

### ISSUE THREAD

**Issue by BobHasNoSoul** [deluan/navidrome#103]
Hi there, i tested navidrome and really love it, simple light weight and awesome addition to my home server setup. 

I have one suggestion / issue

The ability to add a base url to navidrome so it can be accessed at a sub directory 

I.e. myawesomedomain.com/music 

I did attempt this with nginx but this failed to work (as a work around i grabbed a free subdomain from my provider to go to music.myawesomedomain.com) however i would love to have it as a /music 

I can post the nginx config i used if needed but im sure its down it a call back to root instead of a base url.

This was running on a Pi4 b 4Gb ram with nginx 1.17.6

Thanks and great work

**Comment by deluan** [comment]
Thanks for trying Navidrome and thanks for opening the issue. I'll take a look at this.

**Comment by deluan** [comment]
This has to be broke up into the two components of Navidrome:

1) **Server**: for the server part, you can easily configure the base url externally, using some nginx/apache/caddy config magic. Ex for Caddy:
```
    labels:
      caddy.address: 'mydomain.com/navidrome'
      caddy.proxy: '/ navidrome:4533'
      caddy.proxy.without: /navidrome
      caddy.proxy.transparent:
      caddy.proxy.websocket:
```
With the above configuration in my `docker-compose.yml`, I was able to configure my subsonic clients with the URL: https://mydomain.com/navidrome. Worked like a charm.

2) **UI**: this may prove to be very challenging, as create-react-app (used in the UI) does not support changing the base url at runtime: https://github.com/facebook/create-react-app/issues/2353. There are some workarounds suggested in that issue, I'll spent some time trying them and see if there's anything that would help us.
