### ISSUE TITLE
Docker Installation

### ISSUE THREAD

**Issue by joker32** [deluan/navidrome#186]
Can someone please explain to me which steps have to be performed for the installation via docker?
Thanks!

**Comment by deluan** [comment]
### Using `docker-compose` :

1) Create a `docker-compose.yml` file with the following content (or add the `navidrome` service to your existing file):
```
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # All options with their default values:
      ND_SCANINTERVAL: 1m
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 30m
      ND_BASEURL: ""
    volumes:
      - "./data:/data"
      - "/path/to/your/music/folder:/music:ro"
```
2) Remeber to change the `volumes` paths to your local paths. `/data` is where Navidrome will store its DB and cache, `/music` is where your music files are stored. 
3) Customize other `environment` variables as needed. See more options in the [documentation](https://www.navidrome.org/docs/usage/configuration-options/)
4) Start it with `docker-compose up -d`

### Using `docker` command line tool:
```
$ docker run -d \
   --name navidrome \
   --restart=unless-stopped \
   -v /path/to/music:/music \
   -v /path/to/data:/data \
   -p 4533:4533 \ 
   deluan/navidrome:latest
```
Environment variables can be set with `-e` parameter. Ex: `-e ND_SESSIONTIMEOUT=24h`

After starting Navidrome with one of the above options, read the final steps from the [documentation site](https://www.navidrome.org/docs/getting-started/)

Let me know if this helps
