### ISSUE TITLE
Docker: avoid using root in container

### ISSUE THREAD

**Issue by Wonderfall** [deluan/navidrome#349]
Hi! First of all, great work! :)
I read the Dockerfile and the [documentation](https://www.navidrome.org/docs/installation/docker/), and also tried `ps aux` inside the container: it hit me that `root` is being used by default in the container. That could be a security issue, and in general, the less permissions the better.

I could open a PR, but I want your opinion first. There are a few ways to avoid using `root`, but basically I think the documentation should just tell to add a `user` option before running the container (like [Jellyfin documentation](https://jellyfin.org/docs/general/administration/installing.html#docker) does).

Here's my working `docker-compose.yml` for Navidrome:

```
  navidrome:
    image: deluan/navidrome
    container_name: navidrome
    restart: unless-stopped
    user: 1000:1000
    security_opt:
      - no-new-privileges:true
    volumes:
      - /home/docker/navidrome:/data
      - /home/media/Albums:/music:ro
    networks:
      - http_network
    labels:
      # My Traefik labels
````

No root processes with that and everything works flawlessly. :)
