### ISSUE TITLE
DB locking issues

### ISSUE THREAD

**Issue by alex-phillips** [deluan/navidrome#43]
So I'm using a custom web UI that supports subsonic API servers. My client mimics the classic iTunes UI so to populate the library I have to make a lot of API requests to retrieve all information. It looks like every time a Subsonic API endpoint is hit, you're updating the DB with 'last access time'. I'm not sure if this is the only issue, but a good portion of the API calls I'm making are failing due to this locking issue. (Some are also 'Invalid login' messages, but not sure if that's related or something else).

If you want to test it out, here's the docker command to run my client. My library is pretty massive (over 80k songs) so this issue may only be a problem on larger libraries.

```
version: '3'
services:
  qooxtunes:
    container_name: qooxtunes
    image: alexphillips/qooxtunes
    ports:
      - 80:80
      - 443:443
```
