### ISSUE TITLE
Cannot write to Docker volume using Azure File driver

### ISSUE THREAD

**Issue by waymondo** [deluan/navidrome#676]
I am trying to deploy a Navidrome Docker instance on Azure. I'm able to get the Docker container running remotely, as well as read music from an Azure File Share volume using [the instructions outlined here](https://docs.docker.com/engine/context/aci-integration/#using-azure-file-share-as-volumes-in-aci-containers). If I don't specify a volume for the `/data` folder, everything works well, but naturally it gets nuked on a subsequent `docker compose up`. However, when I try to specify an Azure File share volume for the data folder, I get the log error below:

```
 _   _             _     _
| \ | |           (_)   | |
|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
                           Version: 0.39.0 (f2a8308)
time="2020-12-06T05:29:13Z" level=error msg="Error disabling foreign_keys" error="database is locked"
```

To the best of my knowledge, the container instance should have write access to this volume. On Azure, I see the `navidrome.db` file is created but is 0 bytes. Here's the relevant bits from my `docker-compose.yml`:

```
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      ND_PORT: 80
    volumes:
      - "data:/data:rw"
      - "music:/music:ro"
volumes:
  music:
    driver: azure_file
    driver_opts:
      share_name: navidrome
      storage_account_name: navidrome
  data:
    driver: azure_file
    driver_opts:
      share_name: navidrome-data
      storage_account_name: navidrome

```

Thank you so much for this excellent package, and I'd appreciate any insights you might have. I'm quite new to Docker and I apologize in advance if it seems these issues lay outside the responsibilities of Navidrome.

This is what I get when I set the log level to `trace`:

```
 _   _             _     _
| \ | |           (_)   | |
|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
                           Version: 0.39.0 (f2a8308)

Loaded configuration from '': &conf.configOptions{
time="2020-12-06T05:23:15Z" level=debug msg="Opening DataBase" dbPath="/data/navidrome.db?cache=shared&_busy_timeout=15000&_journal_mode=WAL&_foreign_keys=on" driver=sqlite3
    ConfigFile:                 "",
    Address:                    "0.0.0.0",
    Port:                       80,
    MusicFolder:                "/music",
    DataFolder:                 "/data",
    DbPath:                     "/data/navidrome.db?cache=shared&_busy_timeout=15000&_journal_mode=WAL&_foreign_keys=on",
    LogLevel:                   "debug",
    ScanInterval:               300000000000,
    SessionTimeout:             86400000000000,
    BaseURL:                    "",
    UILoginBackgroundURL:       "https://source.unsplash.com/random/1600x900?music",
    EnableTranscodingConfig:    false,
    EnableDownloads:            true,
    TranscodingCacheSize:       "100MB",
    ImageCacheSize:             "0",
    AutoImportPlaylists:        true,
    SearchFullString:           false,
    IgnoredArticles:            "The El La Los Las Le Les Os As O A",
    IndexGroups:                "A B C D E F G H I J K L M N O P Q R S T U V W X-Z(XYZ) [Unknown]([)",
    ProbeCommand:               "ffmpeg %s -f ffmetadata",
    CoverArtPriority:           "embedded, cover.*, folder.*, front.*",
    CoverJpegQuality:           75,
    UIWelcomeMessage:           "",
    EnableGravatar:             false,
    GATrackingID:               "",
    AuthRequestLimit:           5,
    AuthWindowLength:           20000000000,
    Scanner:                    conf.scannerOptions{Extractor:"taglib"},
    DevLogSourceLine:           false,
    DevAutoCreateAdminPassword: "",
    DevPreCacheAlbumArtwork:    false,
    DevFastAccessCoverArt:      false,
    DevOldCacheLayout:          false,
    DevActivityPanel:           false,
}
```
