### ISSUE TITLE
Navidrome cant play any Song from this album

### ISSUE THREAD

**Issue by quotengrote** [deluan/navidrome#730]
Hi, 

thx for your great Work.

I have an Navidrome-Instance within Docker.
It works great but this album cant be played:
- https://mgrote.next-cloud.org/index.php/s/q9PQo829GQt8gE2

## Docker-Compose: 
```
version: '3'
services:
######## navidrome-mg ########
  navidrome-mg:
    container_name: "navidrome-mg"
    image: deluan/navidrome:latest
    restart: always
    environment:
      - ND_SCANINTERVAL=15m
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
      - ND_MUSICFOLDER=/music
      - ND_DATAFOLDER=/data
      - ND_TRANSCODINGCACHESIZE=500MB
      - ND_IMAGECACHESIZE=100MB
      - ND_AUTOIMPORTPLAYLISTS=false
#      - ND_UILOGINBACKGROUNDURL
#      - ND_LASTFM_APIKEY=766f890f25df0c4d6888f8a20f6402af
#      - ND_LASTFM_SECRET=793bb020c96eb438e32f166e2416d22d
      - ND_LASTFM_LANGUAGE="de"
      - ND_BASEURL=/mg
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - musik_smb_mg:/music:ro
      - data:/data
    networks:
      - proxy
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.http.routers.navidrome-mg.rule=Host(`audio.mXXXXXXXX.net`)&&PathPrefix(`/mg`)
      - traefik.enable=true
      - traefik.http.routers.navidrome-mg.tls=true
      - traefik.http.routers.navidrome-mg.tls.certresolver=resolver_letsencrypt
      - traefik.http.routers.navidrome-mg.entrypoints=websecure
      - traefik.http.services.navidrome-mg.loadbalancer.server.port=4533
    ports:
      - "4533:4533"


######## Volumes ########
volumes:
  data:
  musik_smb_mg: # Verzeichnis in restic aus Backup ausnehmen!
    driver: local
    driver_opts:
      type: "cifs"
      o: "user=navidrome,password=XXXXXXXX"
      device: "//192.168.2.36/musik/Musik"
######## Networks ########
networks:
  proxy:
    external: true

```
